# Generated by Django 5.1.2 on 2024-10-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.TextField()),
                ('codigo_barra', models.TextField()),
                ('precio_bruto', models.IntegerField()),
                ('precio_neto', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('stock_critico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.venta')),
            ],
        ),
    ]
