# Generated by Django 5.1.2 on 2024-10-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderVenta',
            new_name='OrdenVenta',
        ),
    ]
