# Generated by Django 5.1.2 on 2024-10-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_rename_orderventa_ordenventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.TextField(null=True),
        ),
    ]
