# Generated by Django 5.1.2 on 2024-10-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alerta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.TextField(null=True),
        ),
    ]
