# Generated by Django 5.1.2 on 2024-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_producto_alerta_producto_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('telefono', models.TextField()),
                ('email', models.TextField()),
                ('direccion', models.TextField()),
                ('es_eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='es_eliminado',
            field=models.IntegerField(default=0),
        ),
    ]
