# Generated by Django 5.1.2 on 2024-10-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_proveedor_producto_es_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.TextField(verbose_name='Codigo Barra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_bruto',
            field=models.IntegerField(verbose_name='Precio Bruto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.TextField(verbose_name='SKU'),
        ),
    ]
