# Generated by Django 5.1.2 on 2024-10-30 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_producto_codigo_barra_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='alerta',
            field=models.BooleanField(default=False, verbose_name='Alerta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_eliminado',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_neto',
            field=models.IntegerField(verbose_name='Precio Neto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_critico',
            field=models.IntegerField(verbose_name='Stock Critico'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.TextField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='es_eliminado',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.TextField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.TextField(verbose_name='Telefono'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False, verbose_name='')),
                ('fecha_recepcion', models.TextField(verbose_name='Fecha Recepcion')),
                ('total_pedido', models.TextField(verbose_name='Total Pedido')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
