# Generated by Django 5.1.2 on 2024-10-30 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_alter_producto_alerta_alter_producto_es_eliminado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id_pedido_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_bruto', models.IntegerField(verbose_name='Precio Bruto')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_inicial', models.IntegerField(verbose_name='Cantidad Inicial')),
                ('cantidad_actual', models.IntegerField(verbose_name='Cantidad Actual')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
            ],
        ),
    ]
