# Generated by Django 5.1.2 on 2024-10-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_pedidoproducto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.TextField()),
                ('nombre_producto', models.TextField()),
                ('sku', models.TextField()),
                ('precio_bruto', models.IntegerField()),
                ('precio_neto', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'producto_detalle',
                'managed': False,
            },
        ),
    ]
