# Generated by Django 5.1.2 on 2024-10-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_productodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_proveedor',
            field=models.TextField(verbose_name='Proveedor'),
        ),
    ]
