# Generated by Django 5.1.2 on 2024-11-09 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_pedido_id_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='')),
                ('fecha_salida', models.DateTimeField()),
                ('monto_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoSalida',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSalidaInventario',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_bruto', models.IntegerField(verbose_name='Precio bruto')),
                ('sub_total', models.IntegerField(verbose_name='Sub total')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
                ('id_salida_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.salidainventario')),
            ],
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='id_tipo_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tiposalida'),
        ),
    ]
