# Generated by Django 5.1.2 on 2024-11-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_pedido_id_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_name', models.TextField(verbose_name='Proveedor')),
                ('fecha_recepcion', models.TextField(verbose_name='Fecha Recepcion')),
                ('total_pedido', models.TextField(verbose_name='Total Pedido')),
            ],
            options={
                'db_table': 'pedido_view',
                'managed': False,
            },
        ),
    ]
