# Generated by Django 5.1.2 on 2024-11-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_pedidoview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosTableView',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='')),
                ('proveedor', models.TextField(verbose_name='Proveedor')),
                ('fecha_recepcion', models.TextField(verbose_name='Fecha Recepcion')),
                ('total_pedido', models.TextField(verbose_name='Total Pedido')),
            ],
            options={
                'db_table': 'pedidos_view',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PedidoView',
        ),
    ]
