# Generated by Django 5.1.2 on 2024-11-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_pedidostableview_delete_pedidoview'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidosProductosView',
            fields=[
                ('id_pedido', models.TextField(primary_key=True, serialize=False, verbose_name='')),
                ('codigo_barra', models.TextField(verbose_name='Codigo Barra')),
                ('nombre_producto', models.TextField(verbose_name='Nombre Producto')),
                ('cantidad', models.TextField(verbose_name='')),
                ('precio_producto', models.TextField(verbose_name='')),
                ('precio_total', models.TextField(verbose_name='')),
                ('precio_actual_venta', models.TextField(verbose_name='')),
            ],
            options={
                'db_table': 'pedidos_productos_view',
                'managed': False,
            },
        ),
    ]
