# Generated by Django 5.1.2 on 2024-11-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_pedidosproductosview'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.TextField(null=True, verbose_name='Marca'),
        ),
    ]
