# Generated by Django 5.1.2 on 2024-11-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_salidainventario_tiposalida_productosalidainventario_and_more'),
        ('administracion', '0014_producto_marca'),
    ]

    operations = [
    ]
