# Generated by Django 5.1.2 on 2024-11-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_merge_20241111_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposalida',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='tiposalida',
            name='tipo',
            field=models.TextField(null=True, verbose_name='Tipo'),
        ),
    ]
