# Generated by Django 5.1.2 on 2024-11-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_remove_tiposalida_descripcion_tiposalida_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposalida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
