# Generated by Django 5.1.2 on 2024-11-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_alter_tiposalida_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidainventario',
            name='monto_total',
        ),
    ]
