# Generated by Django 5.1.2 on 2024-11-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0018_remove_salidainventario_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosalidainventario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
