# Generated by Django 5.1.2 on 2024-11-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_alter_productosalidainventario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='productoDetalleStockView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.TextField(verbose_name='Producto')),
                ('precio_bruto', models.IntegerField(verbose_name='Precio')),
                ('stock_actual', models.IntegerField(verbose_name='Stock')),
                ('stock_critico', models.IntegerField(verbose_name='Stock Critico')),
                ('diferencia', models.TextField(verbose_name='Fecha Vencimiento Proxima')),
            ],
            options={
                'db_table': 'producto_detalle_stock_view',
                'managed': False,
            },
        ),
    ]
