# Generated by Django 5.1.2 on 2024-11-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_productodetallestockview'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockResumenPedidosView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='')),
                ('nombre_proveedor', models.TextField(verbose_name='Nombre Proveedor')),
                ('stock_compra', models.TextField(verbose_name='Stock Compra')),
                ('total_pedido', models.IntegerField(verbose_name='Total pedido')),
                ('fecha_recepcion', models.IntegerField(verbose_name='Fecha Recepcion')),
            ],
            options={
                'db_table': 'stock_resumen_pedidos_view',
                'managed': False,
            },
        ),
    ]
